name: Publish Package to nuget

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  build:
    env:
      BUILD_CONFIG: Release
      SOLUTION: 'intacct-sdk-net.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x

    - name: Ensure GitHub NuGet Source
      run: nuget sources add -name github -source https://nuget.pkg.github.com/Viabl/index.json -username gavintaylor -password ${{ secrets.INTACCT_PUB_PACKAGE_DEPLOY_PAT }} -StorePasswordInClearText
        
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      
    - name: Pack
      run: dotnet pack
      
    - name: Publish to NuGet
      run: nuget push **\*.nupkg -Source 'github' -ApiKey ${{secrets.INTACCT_PUB_PACKAGE_DEPLOY_PAT}}
